### ISSUE TITLE
Header files not found with emacs-ccls, but works fine at vscode.

### ISSUE THREAD

**Issue by woofhyx** [MaskRay/emacs-ccls#101]
I am using spacemacs, I want to use ccls on Physx project. 
In the project root, I have compile_commands.json generate from cmake export, I ran "ccls -index .", store the index files and I use vscode to test ccls, all behave well. The cache directory is saved at .ccls-cache by default. But in emacs, the emacs-ccls says file not found error. Emacs + lsp + emacs-ccls works fine with my other projects. 
![image](https://user-images.githubusercontent.com/18051074/93668480-0e124f80-fabf-11ea-9c0a-948438be9e52.png)

**Comment by MaskRay** [comment]
Since it works for VSCode, it is assuredly a client side issue.

https://github.com/MaskRay/ccls/wiki/Debugging#logs Worth comparing the `initializationOptions:` line after setting `--log-path=`
