### ISSUE TITLE
 user-error Could not find ccls project root

### ISSUE THREAD

**Issue by losper** [MaskRay/emacs-ccls#12]
ccls已经编译完成，并通过exec执行。
emacs-ccls也通过melpa安装
项目的compile_command.json通过cmake生成，并ln -s 软链接了。
但是打开一个cpp文件后，出现 user-error Could not find ccls project root提示，请问是否还有其他未配置的内容？

**Comment by MaskRay** [comment]
Can you run `M-: (projectile-project-root) RET`?

You need some indicator to let projectile know about the project (e.g. `.git`)

**Comment by losper** [comment]
Tks for your advice,it worked.
