### ISSUE TITLE
Goto to underlying type

### ISSUE THREAD

**Issue by moshohayeb** [MaskRay/emacs-ccls#13]
Is there a way for ccls/lsp to go to the underlying type definition.

Example
```
#include <stdio.h>

typedef struct lcore_s lcore_t;

struct lcore_s {
    int a;
    int b;
};

int
main(int argc, char **argv) {
    lcore_t lcore;
    return 0;
}
```

When at lcore_|t lcore and any of these

- lsp-goto-type-definition
- lsp-ui-peek-find-definitions

Would take me to the typedef, is there a way to go to the struct definition directly without hopping around? 

Thanks

**Comment by MaskRay** [comment]
Thanks for reporting. I have just improved `textDocument/typeDefinition`.

* When point is at a variable, go to its type definitions (or declarations if definitions do not exist)
* When point is at a typedef, goto its referenced type.

When you are at `lcore_t <point>lcore;` You may execute `lsp-goto-type-definition` twice to get to `struct lcore_s`.

I understand that you may want to go to `struct lcore_s` without the extra hopping, but I'm not convinced ccls should do it.

**Comment by moshohayeb** [comment]
Understood,

Is this something that can be implemented via $ccls/xxx or is this an inherent limitation in the daemon?
