### ISSUE TITLE
bogus autocomplete and index

### ISSUE THREAD

**Issue by dlyr** [MaskRay/emacs-ccls#15]
Hi,
I'm trying to setup my configuration, and get some trouble with ccls+lsp+company

First test an a unique file, give completion, but when accept a completion, the text is not what expected see here:
![capture d ecran de 2018-10-08 09-45-51](https://user-images.githubusercontent.com/11328509/46597106-05492e80-cadf-11e8-8ff4-cd74901774b6.png)
after selecting the first entry:
![capture d ecran de 2018-10-08 09-46-05](https://user-images.githubusercontent.com/11328509/46597102-037f6b00-cadf-11e8-9b99-a34ed874d352.png)
On this simple example, vanilla company perform well.

The other problem I face is using a bigger project, ccls seems to run (as I can see from the log file), but the proposed completion are totally wrong. reference navigation seems to me ok btw.

I new to ccls and lsp, so feel free to ask any relevant information and what I should test to resolve the situation.
I'm using vanilla emacs (no spacemacs nor doom...)

**Comment by MaskRay** [comment]
Have you installed company-lsp?

```elisp
(defun company-lsp--client-capabilities ()
  "Return the extra client capabilities supported by company-lsp."
  (when company-lsp-enable-snippet
    '(:textDocument (:completion (:completionItem (:snippetSupport t))))))
```

Can you check if `M-: (lsp--client-capabilities)` contains `(:snippetSupport t)`?

When it is true, ccls uses LSP snippets `$1 $0 ...`. These placeholders will cause trouble if you don't configure `company-lsp` in `company-backends`.

**Comment by dlyr** [comment]
Thanks for your reply seems that `company-lsp` is installed.

```emacs-lisp
company-backends is a variable defined in ‘company.el’.
Its value is (company-lsp company-bbdb company-nxml company-css company-eclim company-semantic company-clang company-xcode company-cmake company-capf company-files
	     (company-dabbrev-code company-gtags company-etags company-keywords)
	     company-oddmuse company-dabbrev)
```
and 
```emacs-lisp
(lsp--client-capabilities)

(:workspace (:applyEdit t :executeCommand (:dynamicRegistration t)) :textDocument (:synchronization (:willSave t :didSave t :willSaveWaitUntil t) :documentSymbol (:symbolKind (:valueSet [1 2 3 4 5 6 7 8 9 10 11 12 ...]) :hierarchicalDocumentSymbolSupport t) :formatting (:dynamicRegistration t) :codeAction (:dynamicRegistration t) :completion (:completionItem (:snippetSupport t))))
```

For the second issue, I will wait to have this working and try to give you more informations.

**Comment by dlyr** [comment]
btw 
```emacs-lisp
(setq ccls-extra-init-params '(:client (:snippetSupport :json-false)))
``` 
do not change the behavior

**Comment by MaskRay** [comment]
> (setq ccls-extra-init-params '(:client (:snippetSupport :json-false)))

Since Sep 14, the initialization option `client.snippetSupport: false` will instruct ccls to disable LSP snippets in completion items.

Can you use `strace -e write -f -p $(pgrep -fn ccls)` or `sysdig -As9999 --unbuffered -p '%evt.time %evt.buffer' "proc.exe contains ccls and fd.type=pipe"` to dump `textDocument/completion` responses?

```javascript
{"jsonrpc":"2.0","id":11,"result":{"isIncomplete":false,"items":[{"label":"result : struct Result","kind":5,"detail":"Out_cclsInfo","sortText":"...........","filterText":"result","insertText":"result","insertTextFormat":1,"textEdit":{"range":{"start":{"line":64,"character":8},"end":{"line":64,"character":8}},"newText":"result"},"additionalTextEdits":[]}
```

**Comment by dlyr** [comment]
Packages version : 
`company-lsp        20180917.2244 installed             Company completion backend for lsp-mode.`
`ccls               20181007.524  installed             ccls client for lsp-mode`
`$ git log      ea8f6cb8 (HEAD -> master, origin/master, origin/HEAD) Misc`

I could not install sysdig (not in debian buster repository as I write these lines ...)
So here is what I get with strace (repages without ascii code)

`Content-Length: 466....{"jsonrpc":"2.0","id":6,"result":{"isIncomplete":false,"items":[{"label":"bar(int a, double b, std::string c) -> void","kind":2,"detail":"foo","sortText":"...........","insertText":"bar(${1:int a}, ${2:double b}, ${3:std::string c})$0","filterText":"bar","insertTextFormat":2},{"label":"bar2(double a, double b) -> void","kind":2,"detail":"foo","sortText":"........../","insertText":"bar2(${1:double a}, ${2:double b})$0","filterText":"bar2","insertTextFormat":2}]}}`

and with `(setq ccls-extra-init-params '(:client (:snippetSupport :json-false)))`
`Content-Length: 387....{"jsonrpc":"2.0","id":7,"result":{"isIncomplete":false,"items":[{"label":"bar(int a, double b, std::string c) -> void","kind":2,"detail":"foo","sortText":"...........","insertText":"bar(","filterText":"bar","insertTextFormat":1},{"label":"bar2(double a, double b) -> void","kind":2,"detail":"foo","sortText":"........../","insertText":"bar2(","filterText":"bar2","insertTextFormat":1}]}}`

Seems coherent with what you expect right ?

But the final insertion still insert the `->void` for instance. Btw the behavior is not the same when strace is running (I could not guess why), the completion is just `bar(` and stops.

**Comment by MaskRay** [comment]
> So here is what I get with strace (repages without ascii code)
>
> "insertText":"bar(${1:int a}, ${2:double b}, ${3:std::string c})$0"

This is expected when snippetSupport is enabled (with company-lsp installed)

> and with (setq ccls-extra-init-params '(:client (:snippetSupport :json-false)))
> 
> "insertText":"bar("

This is also correct. When snippetSupport is disabled, only text before the first placeholder is inserted.

> But the final insertion still insert the ->void for instance.

This is the `snippetSupport: false` case. It couldn't happen. Please make sure company-lsp is indeed chosen as the only `company-backends` item (you can add more when you get a usable configuration).

**Comment by dlyr** [comment]
Issue solved:
I first update ccls (and then see textEdit part in `company-lsp--post-completion` message which was not the case before). Then I get inserted `@{$1` chars instead of snippet completion

**Then I install and activate yasnippet, I just don't get that I have to to get nice completion working.**

I will test now the other issue I have and try to give you proper way to reproduce.
Thanks for all.
++ d
