### ISSUE TITLE
SegFault while edditing commit message on Magit

### ISSUE THREAD

**Issue by julienJean99** [MaskRay/emacs-ccls#19]
Expected behaviour: not crash emacs

The behaviour observed: 
    when opening the commit message buffer if I stay too long (less then a minute) it crashes emacs

Reproduce the issue.: it started happening after I installed CCLS and start to edit commit message

M-x magit-version RET
Magit 20180720.1712, Git 2.13.6, Emacs 25.3.1, gnu/linux

I doubt that it would be of any use but here is the stack trace:
Fatal error 6: Aborted
Backtrace:
emacs[0x50abde]
emacs[0x4f12f9]
emacs[0x50ac83]
emacs[0x4ad2c8]
emacs[0x444ed7]
emacs[0x44458e]
emacs[0x444712]
emacs[0x447c7d]
emacs[0x44248f]
emacs[0x532304]
emacs[0x564173]
emacs[0x59c523]
emacs[0x56649d]
emacs[0x563feb]
emacs[0x59c523]
emacs[0x56649d]
emacs[0x563feb]
emacs[0x5642b8]
emacs[0x563796]
emacs[0x4f1984]
emacs[0x562dad]
emacs[0x4f6567]
emacs[0x4ffcfb]
emacs[0x5635e2]
emacs[0x4f1714]
emacs[0x563561]
emacs[0x4f16ab]
emacs[0x4f5f67]
emacs[0x4f628a]
emacs[0x41a09c]
/lib64/libc.so.6(__libc_start_main+0xea)[0x7fce63cda88a]
emacs[0x41ab8a]
eAborted (core dumped)

I'm also posting the issue on the Magit GitHub

**Comment by MaskRay** [comment]
This looks like an upstream issue.
