### ISSUE TITLE
Could not find emacs-ccls in melpa

### ISSUE THREAD

**Issue by samrayleung** [MaskRay/emacs-ccls#2]
Hey, MaskRay, I want to give `ccls` a try, switching from `cquery` to `ccls`. But when I follow the instrument in `ccls` wiki, I could not install `ccls` from melpa. It seems `emacs-ccls` doesn't host in melpa,right?

**Comment by MaskRay** [comment]
Still waiting for https://github.com/melpa/melpa/pull/5405

Before it is merged, you may use:

```elisp
;; https://github.com/MaskRay/Config/blob/master/home/.config/doom/modules/private/my-cc/config.el
(use-package! ccls
  :load-path "~/Dev/Emacs/emacs-ccls"
  :init (add-hook 'c-mode-common-hook #'+ccls//enable)
  :config
  ;; overlay is slow
  ;; Use https://github.com/emacs-mirror/emacs/commits/feature/noverlay
  (setq ccls-sem-highlight-method 'font-lock)
  (ccls-use-default-rainbow-sem-highlight)
  (setq ccls-extra-init-params
        '(:completion (:detailedLabel t) :xref (:container t)
                      :diagnostics (:frequencyMs 5000)))

  (require 'projectile)
  (add-to-list 'projectile-globally-ignored-directories ".ccls-cache")

  (evil-set-initial-state 'ccls-tree-mode 'emacs)
  (set! :company-backend '(c-mode c++-mode) '(company-lsp))
  )
```

**Comment by samrayleung** [comment]
Sorry for missing the FAQ, because I haven't set `.ccls-root` in the root project, so `ccls` just generates `.ccls-cache` for each subproject. Even though I am not familiar with `ccls/emacs-ccls`, I think your explanation is clear enough.

**Comment by MaskRay** [comment]
The PR has been merged.

https://melpa.org/#/ccls

**Comment by samrayleung** [comment]
Congrats!
