### ISSUE TITLE
flycheck macro redefined and no syntax highlighting

### ISSUE THREAD

**Issue by dlyr** [MaskRay/emacs-ccls#20]
Hi,
I have an unexpected behavior but do not know where to search for a solution.

On a quite big projet, with some header files, I got warnings (on the flymake sense) on more or less "random" lines that state "ccls : '_DEBUG' macro redefined,
and the "ccls : 'DEBUG' macro redefined.

Which is actually the case (in the project, but not in the given file). With in a top header I have:
``` c++
// Make sure all "debug" macros are defined
#if defined (DEBUG) || defined(_DEBUG) || defined (CORE_DEBUG) // ------- Debug
#   undef CORE_DEBUG
#   define CORE_DEBUG

#   undef _DEBUG
```

The warning is not a big issue, but the whole header is then not fontified (no syntax highlighting).

Don't know if it's linked, but I also see some warning in '*lsp-ccls stderr*<2>` buffer: 
```
warning: argument unused during compilation: '-Wall'
warning: argument unused during compilation: '-Wextra'
warning: argument unused during compilation: '-pthread'
warning: argument unused during compilation: '-msse3'
warning: argument unused during compilation: '-Wno-sign-compare'
warning: argument unused during compilation: '-Wno-unused-parameter'
warning: argument unused during compilation: '-Wno-deprecated-declarations'
warning: argument unused during compilation: '-D _DEBUG'
warning: argument unused during compilation: '-D CORE_DEBUG'
warning: argument unused during compilation: '-g3'
warning: argument unused during compilation: '-ggdb'
warning: argument unused during compilation: '-Wno-unused-parameter'
warning: argument unused during compilation: '-Wno-deprecated-declarations'
warning: argument unused during compilation: '-g'
warning: argument unused during compilation: '-Wno-ignored-attributes'
warning: argument unused during compilation: '-Wno-misleading-indentation'
warning: argument unused during compilation: '-Wno-unknown-pragmas'
warning: argument unused during compilation: '-std=c++14'
warning: argument unused during compilation: '-c'
```

Feel free to ask any informations or test I can make.
++ d

**Comment by MaskRay** [comment]
> warning: argument unused during compilation: '-Wall'

The command line used in `compile_commands.json` will be more helpful.

https://github.com/MaskRay/ccls/wiki/FAQ#diagnostics-in-headers

**Comment by dlyr** [comment]
```
{
  "directory": "/MY_BUILD_DIR/src",
  "command": "/usr/bin/c++  -DIO_USE_ASSIMP -DIO_USE_CAMERA_LOADER -DIO_USE_TINYPLY -DQT_CORE_LIB -DQT_GUI_LIB -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_XML_LIB -DRA_ENGINE_EXPORTS -DradiumEngine_EXPORTS -I/MY_BUILD_DIR/src -I/MY_PROJECT_DIR/src -I/MY_PROJECT_DIR/Bundle-GNU/3rdPartyLibraries/include -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtOpenGL -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -isystem /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++  -Wall -Wextra  -pthread -msse3 -Wno-sign-compare -Wno-unused-parameter                  -D_DEBUG -DCORE_DEBUG -g3 -ggdb          -g -fPIC   -Wno-ignored-attributes -Wno-misleading-indentation -Wno-unknown-pragmas -fPIC -std=c++17 -o CMakeFiles/radiumEngine.dir/Engine/Component/Component.cpp.o -c /MY_PROJECT_DIR/src/Engine/Component/Component.cpp",
  "file": "/MY_PROJECT_DIR/src/Engine/Component/Component.cpp"
},
```

I just notice I also get some `Error from the Language Server: failed to index MY_SOURCE_FILE (Internal Error)`

**Comment by dlyr** [comment]
Here is a minimal example. The thing is that if compile command have a -DDEBUG that is #undef then #define it produce a ccls warning. I dunno if it's correct or not, but seems strange for me.

[exemple.zip](https://github.com/MaskRay/emacs-ccls/files/2669247/exemple.zip)

**Comment by MaskRay** [comment]
> warning: argument unused during compilation: '-Wall'

I believe you have misconfigured something. 
Change you wrapper script to: `ccls -log-file=/tmp/ccls.log -v=1 "$@"` `-v=1` will give you the command line used to parse files, e.g.

```
12:11:34 indexer2         pipeline.cc:310 I parse /tmp/Downloads/ex/main.cpp
  /usr/bin/c++ -DDEBUG -std=c++17 -o out.o -c /tmp/Downloads/ex/main.cpp  -working-directory=/tmp/Downloads/ex
```

> exemple.zip

This example works fine for me.

If you have some non self-contained header files, the PR just gets merged may help you https://github.com/MaskRay/ccls/pull/171

e.g. `.ccls`:
```
%compile_commands.json
%h -DH
```
