### ISSUE TITLE
ccls won't start after todays update

### ISSUE THREAD

**Issue by defphil** [MaskRay/emacs-ccls#21]
After todays update of lsp-mode and ccls, every time I try to start ccls via `M-x lsp-ccls-enable` I get the following error. Before updates everything worked perfectly. 

`command-execute: Autoloading file /Users/phil/.emacs.d/elpa/ccls-20181203.843/ccls.elc failed to define function lsp-ccls-enable
`

Didn't have time too look up if it is lsp or ccls related. So I will this here for now, feel free to close it if it's lsp related.
If it's problem on my part with my emacs config I will post the code from the init.el

Have a nice day!

**Comment by MaskRay** [comment]
It's related to the latest lsp-mode update
See ccls/wiki/Emacs
