### ISSUE TITLE
Improper printing of the function's prototype

### ISSUE THREAD

**Issue by MeschiX** [MaskRay/emacs-ccls#24]
Hi,
Using this package for developing in C, i've found an error in print of funcion prototype at the time of completion using [company-lsp.](url)

I post a screenshot that can explain better than words.

![schermata 2018-12-20 alle 23 07 16](https://user-images.githubusercontent.com/38925459/50318018-f8718f80-04be-11e9-8293-57e56e0bc8e1.png)
Here well shown on popup

![schermata 2018-12-20 alle 23 07 35](https://user-images.githubusercontent.com/38925459/50318112-82b9f380-04bf-11e9-91f0-3c9adeb79ac4.png)
At the completing time `(M-x company-complete)` prototype printing goes wrong.

I could not understand the problem by myself

**Comment by MaskRay** [comment]
You need company-lsp and yasnippet.

I've updated the README.md on https://github.com/emacs-lsp/lsp-mode

```elisp
(use-package lsp-mode
  :commands lsp
  :init
  (setq ...))

(use-package lsp-ui :commands lsp-ui-mode)
(use-package company-lsp :commands company-lsp)
;; use-package yasnippet if it is not required by other packages
```
