### ISSUE TITLE
Enable GNU-indentation?

### ISSUE THREAD

**Issue by lshoravi** [MaskRay/emacs-ccls#25]
When indenting with a region, it automatically places brackets and indentation length to K&R style (or something like that) instead of whatever `c-indent-style` is. On my system, `c-indent-style` is set to `gnu`.

I.e, it goes from:
``` c
if (...) 
  {
....
  }
```

to 
``` c
if (...) {
....
}
```

**Comment by MaskRay** [comment]
The server does not know these Emacs cc-mode variables (e.g. `c-indent-style` `tab-width`).

You can achieve this with:

```zsh
% cat .clang-format
BasedOnStyle: GNU
```

ccls uses clangFormat which reads the file to decide the style.

**Comment by lshoravi** [comment]
Thank you

**Comment by lshoravi** [comment]
I can't actually get this to work.
