### ISSUE TITLE
Automating the generation of compile_commands.json

### ISSUE THREAD

**Issue by Compro-Prasad** [MaskRay/emacs-ccls#28]
Doing this will help in getting started with LSP easily. A command to do this would be enough. I think this can be done with the help of `projectile` and/or `project.el`. By asking the user questions about the command to run to generate the `compile_commands.json` from project root.

**Comment by MaskRay** [comment]
`compile_commands.json` should not be generated automatically.

* Where to put `compile_commands.json`: I usually prefer `$project/Debug` and for CMake-based projects I use `cmake -H. -BDebug -DCMAKE_EXPORT_COMPILE_COMMANDS=YES <other options>`. This operation creates some files that may not be wanted.
* The various `-D*` options. They cannot be known beforehand.
