### ISSUE TITLE
lsp ui

### ISSUE THREAD

**Issue by innerout** [MaskRay/emacs-ccls#3]
Will emacs-ccls support lsp-ui? It is very helpful when somebody is developing in a big codebase.

**Comment by MaskRay** [comment]
emacs-ccls is an adapter of lsp-mode and the server (ccls). lsp-ui provides
some ui enhancement on top of lsp-mode.

"does it support lsp-ui" a client doesn't need anything special to
"support" lsp-ui

i'm using lsp-ui emacs-ccls lsp-mode to navigate llvm codebase.

**Comment by innerout** [comment]
Sorry it was mine mistake i forgot to add .ccls-root as i thought compile_commands.json was sufficient.

**Comment by MaskRay** [comment]
`compile_commands.json` can be in a build directory and using it as a root indicator is not very reliable.

**Comment by innerout** [comment]
Yeah there is no problem. I was used to cquery with only compile_commands.json but that seems to be better having ccls-root.

**Comment by rileyrg** [comment]
Having a compile_commands.json in my build directory one level below the root does not work.

**Comment by myrgy** [comment]
you may try to create symlink:
cd projectRoot
 ln -s  build/compile_commands.json

**Comment by rileyrg** [comment]
Yes, I know and its what I do for now.
