### ISSUE TITLE
Qt headers: strange completion candidates 

### ISSUE THREAD

**Issue by rogorido** [MaskRay/emacs-ccls#36]
Do you have some hint how to configure a project to properly get completion for Qt headers?

**Comment by MaskRay** [comment]
https://github.com/MaskRay/ccls/wiki/Project-Setup

**Comment by rogorido** [comment]
Thanks, the question was not formulated very clear. 

My project has the right setup and I can get completions of Qt classes and methods. But: what I do not get are completions of #include <QtXXX>. Any hint?

**Comment by tamlok** [comment]
@rogorido Could you share how to setup for the completions of Qt classes? I already have `compile_commands.json` at the root of my project, but still fail to get the completions.

**Comment by rogorido** [comment]
I still have this problem...
