### ISSUE TITLE
Find a function's namespace 

### ISSUE THREAD

**Issue by Davidbrcz** [MaskRay/emacs-ccls#39]
Hi,

Is there a way to find the namespace in which a function belong ?

For instance:
```
//C.h
namespace A{namespace B
struct C{void foo();};
}}
```

```
//C.cpp
#include "C.h"
using namespace A::B;
void C::foo(){
// cursor is here,
}
```
With the example above, the namespace command would display A::B (because foo is defined in C, which is in namespace A::B.

Is there a way to it ?

Thanks !
David

**Comment by MaskRay** [comment]
`textDocument/hover` displays that.

The ccls extension `$ccls/navigate` may be handful. https://github.com/MaskRay/ccls/wiki/lsp-mode#ccls-navigate

```elisp
(ccls-navigate "D") ;; roughly sp-down-sexp
(ccls-navigate "L")
(ccls-navigate "R")
(ccls-navigate "U")
```
