### ISSUE TITLE
ccls-freshen-index assertion failed

### ISSUE THREAD

**Issue by innerout** [MaskRay/emacs-ccls#4]
When i am trying to run ccls-freshen-index in a project it fails with 
```Assertion failed: (lsp--workspace-p lsp-cur-workspace)```

**Comment by MaskRay** [comment]
`lsp--cur-workspace` (two dashes) is what lsp-mode uses to track the associated workspace. I'm pretty sure the single dash form name is not used.

**Comment by innerout** [comment]
I copied the message from the Messages buffer. I cannot reproduce it today so probably i should close the issue.

**Comment by MaskRay** [comment]
This function has now been renamed to `M-x ccls-reload`. It will reset the in-memory database to fix inconsistency between disk cache and memory (if exists)
