### ISSUE TITLE
How to reset the project root

### ISSUE THREAD

**Issue by shpark** [MaskRay/emacs-ccls#40]
I want to change or reset the project root, since the location of `compile_commands.json` is moved.

I've tried looking at `M-x customize-group ccls` or removed `.ccls-cache` from the project root directory, however I couldn't find a way to reset the project root of the file.

How can I set a new project root?

**Comment by shpark** [comment]
I managed to reset the project root by deleting `.emacs.d/lsp-session-v1`. However, this seems to be an overkill. Does ccls provide any efficient way for doing this?

**Comment by MaskRay** [comment]
It is `~/.emacs.d/.lsp-session-v1`, not `lsp-session-v1`. There seems no support to delete a session. You may send a feature request to lsp-mode.

**Comment by Hi-Angel** [comment]
For future users: there is a way to reset or change the project root without removing a file.

`~/.emacs.d/.lsp-session-v1` contains a list of strings that are project roots. So you can simply modify it manually and restart emacs and lsp-mode. Just be careful that if you modify it while lsp session is running and you not restart emacs, there's a slight chance you modifications may get overwriten.
