### ISSUE TITLE
How do I make lsp-flycheck-ui support C++17?

### ISSUE THREAD

**Issue by bk322** [MaskRay/emacs-ccls#42]
I'm using latest of everything, but `flycheck` under `lsp-ui` suggest that `ccls` doesn't support C++17:

![017](https://user-images.githubusercontent.com/875273/56082018-69490880-5e1c-11e9-947a-eec77397711e.png)

Where to look for a fix?

**Comment by MaskRay** [comment]
`GCC 6/Clang 6 default to -std=gnu++14`

Make sure your `compile_commands.json` or `.ccls` specifys `-std=c++17` (or `gnu++17`)

**Comment by bk322** [comment]
Indeed, creating `.ccls` in root folder with
```
clang++
%cpp -std=c++17
```

Solves it.

Also, header `#include <iostream>` is clickable, but when I click it nothing happens. Is it supposed to be like that, or do I lack docs available to ccls / lsp?

**Comment by Cerclique** [comment]
I'm having the same issue.
I created `.ccls` file with the same content but that does not solve the problem.

I have the same setup : flycheck / lsp-ui / ccls

Any idea ?
