### ISSUE TITLE
Best way to run ccls with nice

### ISSUE THREAD

**Issue by bb4242** [MaskRay/emacs-ccls#45]
Thanks for ccls, it's great!  I was wondering if there is an easy way run the emacs ccls process with nice (under linux).  My workflow involves frequently changing branches of the code I'm using ccls to index.  Each branch change kicks off a long-running, CPU heavy re-index of the project, and it would be really nice to have this indexing not slow down the rest of the machine.  Any thoughts you have would be appreciated!

**Comment by MaskRay** [comment]
Consider using a [shell script wrapper](https://github.com/MaskRay/ccls/wiki/Install#shell-script-wrapper).
