### ISSUE TITLE
Arguments to a function not shown when point is on it

### ISSUE THREAD

**Issue by Compro-Prasad** [MaskRay/emacs-ccls#5]
A small info about this in the minibuffer would be useful.

**Comment by MaskRay** [comment]
Do you mean `textDocument/signatureHelp`?

Highlighting the current positional argument shall be helpful:
`foo(arg_0, <bold>arg_1</bold>, arg_2)`

But it also raises the question how to display the information of the identifier itself.. textDocument/hover of `arg_1`

**Comment by Compro-Prasad** [comment]
Sorry, my bad. I can get it when I enable `lsp-ui-mode`. It works in my config but fails in spacemacs because two eldocs are shown simultaneously because of which the function prototype eldoc hides itself under the variable eldoc.

**Comment by MaskRay** [comment]
You may be interested at https://github.com/emacs-lsp/lsp-mode/pull/422

I have also recently revamped `textDocument/signatureHelp` in ccls.

```elisp
(defun +my/lsp-ui-doc--eldoc (&rest _)
  (when (and (lsp--capability "documentHighlightProvider")
             lsp-highlight-symbol-at-point)
    (lsp-symbol-highlight))
  (if (evil-insert-state-p)
      (lsp--text-document-signature-help)
      lsp-ui-doc--string-eldoc
      ))

(advice-add #'lsp-ui-doc--eldoc :override #'+my/lsp-ui-doc--eldoc)
```
