### ISSUE TITLE
Wrong completion items

### ISSUE THREAD

**Issue by theFool32** [MaskRay/emacs-ccls#54]
Hi, I'm using doom-emacs with ``(cc +lsp)``.
The completion items seem mixed as below:
![image](https://user-images.githubusercontent.com/3063690/61876150-d04b8280-af1e-11e9-9907-c49d7908dca6.png)
or
![image](https://user-images.githubusercontent.com/3063690/61876301-20c2e000-af1f-11e9-8e90-9525a6d679e1.png)

I use a clean doom-emacs without extra configuration on macos.
ccls is installed by brew.

I also try nvim with coc.nvim. Wrong completion items show up and flash into correct ones.
I am new to emacs and have no idea about how to deal with it.

Thanks.

**Comment by MaskRay** [comment]
The completion items are correct. All of `a`, `b` and `c` are valid.

**Comment by theFool32** [comment]
Why are they correct?
`v` is `vector<int>` while completion items are from struct `Abc`

**Comment by MaskRay** [comment]
Sorry for my oversight. You typed `a.`, deleted `.`, then added `v`. In that case, the stale completion cache will be reused. I have thought about false positives while adding the cache, but your case is convincing enough to justify a change. Fixed by https://github.com/MaskRay/ccls/pull/489
