### ISSUE TITLE
Is there a way to reload the compile_commands.json? (Especially if one did not exist previously)

### ISSUE THREAD

**Issue by DougBeney** [MaskRay/emacs-ccls#55]
I am trying to reload ccls whenever the `compile_commands.json` file is changed.

## Steps to Reproduce:

In this example, I create a really basic Qt5 project. Feel free to reproduce using a library/framework that you are more familiar with.

**Step 1.**: Create `hello.cpp` in empty directory with emacs:

```c++
#include <QString>
int main() { }
```
Result so far: flycheck should display an error on line 1. This is expected.

**Step 2.**: Generate a compile_commands.json and place it in the project root.

`MyProject.pro`:

```
QT += core gui widgets
TARGET = hello
SOURCES += hello.cpp
```

Commands:

```bash
mkdir build
cd build
qmake ../MyProject.pro
bear make # This generates the compile_commands.json
cp compile_commands.json ..
```

**Step 3:** Attempt to reload/restart lsp (or ccls) so your new compile_commands.json is picked up.

I have tried the Emacs functions `lsp-restart-workspace` and `ccls-reload`. I've even tried killing the ccls process to force a restart.

The only solution I have right now is to completely restart emacs.

My lsp config:

```elisp
(use-package lsp-mode
  :hook ((c-mode
          c++-mode
          javascript-mode
          vue-mode
          css-mode) . lsp)
  :config
  (require 'lsp-clients) ;; Multiple language configurations out of the box
  (use-package ccls) ;; C/C++ language server

  (use-package lsp-ui
    :hook (lsp-mode . lsp-ui-mode)
    :config
    ;; Don't use flymake; we'll use flycheck.
    (setq lsp-prefer-flymake nil))

  (use-package company-lsp
    :init
    (push 'company-lsp company-backends)))
```

**Comment by DougBeney** [comment]
I'm not sure what I did, differently, but it works fine now. My latest config is above. Will re-open if the issue comes up again and is reproducible.

**Comment by MaskRay** [comment]
* `(ccls/reload)` (ccls extension notification: `$ccls/reload`) reloads working files (files that the client has sent `textDocument/didOpen`). This is useful if you edit a common header file and you expect all opened files to be re-indexed.
* `workspace/didChangeConfiguration`. You should send this notifcation if `compile_commands.json` is changed. The `$ccls/reload` handlers doesn't check `compile_commands.json`.
* `M-x lsp-restart-workspace`. This restarts the ccls process. It is more heavyweight but you may get used to it if you also use it with other language servers.
