### ISSUE TITLE
Hanging at startup

### ISSUE THREAD

**Issue by skelutten** [MaskRay/emacs-ccls#58]
I got cquery working with emacs and thought I should try ccls to see if there is any performance improvement etc.

At first setup it actually seemed to work, but then after restarting emacs and changing the emacs-ccls configuration it starts hanging with a message that ccls is initializing shown in emacs.
Emacs is frozen as well.
Pressing M-g a few times returns Emacs to normal mode, but lsp/ccls shows symbols as unknown and no lsp functionality working.

The cq.log doesn't show any error. and neither does the ccls buffers in emacs.

I even tried to erase all ccls cache folders and return my configuration to what I had first, but then the problem doesn't go away.

I can run "ccls -index=." in my project without any error.

Any known issue or how can I troubleshoot this?

[06_cpp_lsp.el.txt](https://github.com/MaskRay/emacs-ccls/files/3501253/06_cpp_lsp.el.txt)

**Comment by MaskRay** [comment]
> The cq.log doesn't show any error. and neither does the ccls buffers in emacs.

You have `(setq cquery-extra-args '("--log-file=/tmp/cq.log"))`, but the ccls counterpart is ccls-args.

> I can run "ccls -index=." in my project without any error.

This suggests an Emacs configuration error.
