### ISSUE TITLE
usage question

### ISSUE THREAD

**Issue by lemon0910** [MaskRay/emacs-ccls#6]
I install lsp-ui and emacs-ccls, when I call ccls-call-hierarchy, I can see on the right side, but It won't go to the code. It's static, so how to jump when you move line on the right side.

**Comment by MaskRay** [comment]
`ccls-tree.el`:
```elisp
    (define-key map (kbd "j") #'ccls-tree-next-line)
    (define-key map (kbd "k") #'ccls-tree-prev-line)
```

`<up> <down>` does not move point in the document.

**Comment by lemon0910** [comment]
thanks, I used evil-mode so some key won't work.
