### ISSUE TITLE
How to pass blacklist/whitelist directories to CCLS?

### ISSUE THREAD

**Issue by hisnawi** [MaskRay/emacs-ccls#68]
When using Eglot there is not way to pass blacklist/whitelist directories through ccls-initialization-options per https://github.com/joaotavora/eglot/issues/370

Is there a way to pass this info to CCLS in a different way?

**Comment by MaskRay** [comment]
See `index.initialBlacklist` https://github.com/MaskRay/ccls/wiki/Customization#indexinitialblacklist The counterpart is `index.initialWhitelist`. These files are initially excluded, but index still works after they are opened. (There is also `index.blacklist`)
