### ISSUE TITLE
Warning (lsp-mode): Unknown method: $ccls/setInactiveRegions

### ISSUE THREAD

**Issue by Yevgnen** [MaskRay/emacs-ccls#7]
Hi, I have the following message keep showing in minibuffer

```
Warning (lsp-mode): Unknown method: $ccls/setInactiveRegions
Warning (lsp-mode): Unknown method: $ccls/setInactiveRegions
Warning (lsp-mode): Unknown method: $ccls/setInactiveRegions
```

I tried to update `ccls` to the latest version but the message is still there. Is this a bug? Thanks in advance.

**Comment by MaskRay** [comment]
The method has been renamed. Update ccls and emacs-ccls

**Comment by myrgy** [comment]
Thanks you! That was my issue.
