### ISSUE TITLE
How to pass complex command line arguments via ccls-args?

### ISSUE THREAD

**Issue by sefeng211** [MaskRay/emacs-ccls#72]
Hi I am a Emacs newbie and sorry if this has been documented somewhere. 

I tried to set the arguments as 
`(setq ccls-args '("--log-file=/tmp/ccls_log.txt --init='{\"index\": {\"threads\": 4, \"initialBlacklist\": [\".\"]}}'")) `, 
and this didn't seem to be parsed correctly, as ccls still used all the cores. 

I also tried to do something like 
`(setq ccls-args '("--log-file=/tmp/ccls_log.txt" "--init='{\"index\": {\"threads\": 4, \" initialBlacklist\": [\".\"]}}'"))`,
and this one also didn't work, and the server seemed fail to start. 

Thanks!

**Comment by MaskRay** [comment]
`(setq ccls-args '("--log-file=/tmp/ccls_log.txt" "--init={\"index\": {\"threads\": 4, \" initialBlacklist\": [\".\"]}}"))`

If you write `--init='{...}'` in a shell, the shell will not pass single quotes to the process. You may read some documents about shell quoting.
