### ISSUE TITLE
lsp-flycheck / C++17

### ISSUE THREAD

**Issue by Cerclique** [MaskRay/emacs-ccls#73]
Hi ! 

I'm having the same problem as Issue #42 with the same setup. 
```
clang version 9.0.1
lsp-ui / flycheck / ccls
```

Unfortunately, creating `.ccls` file did not solve the issue.
I also tried to create the file before initializing the project but same result. 

Do you have any idea ?

**Comment by Cenderme** [comment]
I'm having the exact same problem. I also tried to create a compile_commands.json by following the instructions but to no avail.

**Comment by Cerclique** [comment]
@Cenderme, I used [bear](https://github.com/rizsotto/Bear) to automatically generate my `compile_commands.json`. 
After that, no more error and everything working fine.
