### ISSUE TITLE
Function definition lsp:ccls-call-children is void

### ISSUE THREAD

**Issue by fperies** [MaskRay/emacs-ccls#94]
hello,
I'm getting the following error when trying to get call hierarchy tree of a C++ function:
`ccls-call-hierarchy--request-children: Symbol s function definition is void: lsp:ccls-call-children`

**edebugger** points me out the following line:
https://github.com/MaskRay/emacs-ccls/blob/2aea7d0064ce1793d0352dff885d9e6eaca886ce/ccls-call-hierarchy.el#L85

The _*ccls-tree call hierarchy_ buffer remains empty.

Thank you for your support

**Comment by MaskRay** [comment]
My `ccls-call-hierarchy` is good. Have you deleted stale `.elc` files?

**Comment by fperies** [comment]
I use Spacemacs so normally I should not have to remove manually any .elc file but maybe you could give me some procedure so to achieve this.
Or maybe I should disable and enable again layer lsp?

**Comment by fperies** [comment]
This issue is no more observed.
Thanks again for your support

**Comment by fperies** [comment]
This issue is no more observed.
Thanks again for your support

**Comment by fperies** [comment]
This issue is no more observed.
Thanks again for your support

**Comment by fperies** [comment]
This issue is no more observed.
Thanks again for your support

**Comment by fperies** [comment]
This issue is no more observed.
Thanks again for your support

**Comment by fperies** [comment]
This issue is no more observed.
Thanks again for your support

**Comment by fperies** [comment]
This issue is no more observed.
Thanks again for your support

**Comment by fperies** [comment]
This issue is no more observed.
Thanks again for your support

**Comment by fperies** [comment]
This issue is no more observed.
Thanks again for your support
